markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
pygments: true
paginate: 8

safe:  false

#Site config
title: seeksky 的 blog
description: seeksky 的 blog, 一个技术宅征服世界的梦想
keywords: seeksky blog hadoop mapreduce virtualization
url: http://xujinlai.tk
feed: /atom.xml
favicon: /favicon.ico

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: Seeksky
    email: xujinlai@gmail.com
    imageLink: /images/fav.jpg
    simpleIntro: 我是seeksky,本名[徐锦来],虽然现在还是一名研二学生,但是有着技术宅征服世界的梦想
    detailIntro:
      <p>Seeksky是我很早就开始用的网名,到现在估计已经用了10年不止了,至于一开始的时候为什么要使用这个名字已经忘记很久了,但是对于这两个简单单词的组合还是非常喜欢的.</p>
      <p>现在主要做的是云计算基础平台方面的研究,兼顾虚拟化,Hadoop,并行编程框架等等,现在也开始涉足大数据方向,希望有一个好的开始</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/xujinlai
  - class: icon-renren
    url: http://www.renren.com/266080109
  - class: icon-github-alt
    url: http://github.com/xujinlai
  - class: icon-twitter
    url: http://twitter.com/xujinlai
  - class: icon-google-plus
    url: http://google.com/+徐锦来seeksky

#Links
customLinks:
  - item:
    - text: xujinlai的github博客
      url: http://xujinlai.tk
	- text: xujinlai的BAE上的博客(已暂停更新)
      url: http://seeksky.duapp.com
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-46212341-3

#comment config
disqus:
  config: true
  id: xujinlai

duoshuo:
  config: false
  id: zhanxin