title:            Seeksky's Blog
description:      技术宅征服世界(Technique nerds conquer the world)
disqus_shortname: xujinlai
comments: true
share: true
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://jinlaixu.net
relative_permalinks: true


# Owner/author information
owner:
  name:           Jinlai Xu (Seeksky)
  avatar:         avatar.jpg
  bio:            "My name is Jinlai Xu, you can call me Seeksky(my nickname) or Andy(my official english name). My favourite is computer and every thing related to it."
  email:          xujinlai@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        xujinlai
  facebook:       xujinlai
  github:         xujinlai
  stackexchange:  
  linkedin:       xujinlai
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   https://plus.google.com/109742831833154437581
  
# My books
books: 
  - id: TAR-Does-God-Play-Dice
    name: "Thoughts After Reading: History of Quantum Physics: Does God Play Dice?"
    author: "Jinlai Xu"
    abstract: "After reading the book: History of Quantum Physics: Does God Play Dice?, I have many thoughts haunting in my mind. In order to saluting to the scientist participating in the discovering and research of the secret of quantum physics, I wrote this to represent my fealings after reading this book. And this was the first time that I tried to write something in two languages. I will try my best to illustrate my point of view."
    status: in-progress
  - id: gitbook-documentation
    author: "GitBook"
    name: "GitBook Documentation"
    abstract: "This book contains the entire documentation for GitBook (platform and toolchain). GitBook is a tool for building beautiful books using Git and Markdown. It can generate your book in multiple formats: PDF, ePub, mobi or as a website."
    status: recommend
  - id: ProGit
    author: "Scott Chacon"
    name: "Pro Git"
    abstract: "This is a GitBook version of the Scott Chacon's book: Pro Git. The entire Pro Git book, written by Scott Chacon and published by Apress, is available here. All content is licensed under the Creative Commons Attribution Non Commercial Share Alike 3.0 license. Print versions of the book are available on Amazon.com. This book is also an example of a book that can be generated in multiple languages. WARNING: This repo is automatically generated by progit-to-gitbook. Please submit all pull requests to Pro Git."
    status: recommend

# Background image to be tiled on all pages
background: ps_neutral.png
feature: http://seeksky.qiniudn.com/19.jpg-clip.jpg
qiniu: http://seeksky.qiniudn.com

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-46212341-5
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  #- title: BAE Blog(abandon)
  #  url: http://seeksky.duapp.com
  # external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
pygments:    true
markdown:    kramdown

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough","superscript"]

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year/:month/:day/:title 

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]